# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: SimpleDemo

on: workflow_dispatch

permissions:
  contents: write
  pages: write

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install firefox
      run: apt-get install -y firefox

    - name: Download geckodriver
      run: |
            wget "https://github.com/mozilla/geckodriver/releases/download/v0.35.0/geckodriver-v0.35.0-linux-aarch64.tar.gz"
            tar -xzf "geckodriver-v0.35.0-linux-aarch64.tar.gz"
        
    - name: Install dependencies
      run: |
        pip install selenium robotframework robotframework-seleniumlibrary
        
    - name: Run robotframework
      run: |
        robot -d results selenium_demo.robot

    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
          name: test-results
          path: results
             
